import { Car } from './types';

export const mockCars: Car[] = [
  // Premium Auto Gallery (Los Angeles) - 17 cars
  {
    id: 'car-1',
    make: 'Tesla',
    model: 'Model S',
    year: 2024,
    price: 89990,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    dealershipId: 'dealership-1',
    features: ['Autopilot', 'Premium Audio', 'Glass Roof', 'Heated Seats', 'Wireless Charging'],
    color: 'Pearl White',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },
  {
    id: 'car-2',
    make: 'BMW',
    model: 'X5',
    year: 2023,
    price: 67500,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    dealershipId: 'dealership-1',
    features: ['Navigation', 'Leather Seats', 'Sunroof', 'Blind Spot Monitor', 'Premium Audio'],
    color: 'Alpine White',
    mileage: 12000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-3',
    make: 'Mercedes-Benz',
    model: 'C-Class',
    year: 2024,
    price: 55900,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    dealershipId: 'dealership-1',
    features: ['MBUX Infotainment', 'LED Headlights', 'Heated Seats', 'Apple CarPlay', 'Lane Keeping Assist'],
    color: 'Obsidian Black',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },
  {
    id: 'car-4',
    make: 'Audi',
    model: 'Q7',
    year: 2023,
    price: 72000,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    dealershipId: 'dealership-1',
    features: ['Virtual Cockpit', 'Quattro AWD', 'Panoramic Sunroof', 'Premium Audio', 'Adaptive Cruise Control'],
    color: 'Glacier White',
    mileage: 8500,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-5',
    make: 'Porsche',
    model: '911',
    year: 2024,
    price: 115000,
    seats: 4,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c5303bea?w=800',
    dealershipId: 'dealership-1',
    features: ['Sport Chrono Package', 'PASM', 'Premium Audio', 'Sport Exhaust', 'Ceramic Brakes'],
    color: 'Guards Red',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Manual',
    bodyType: 'Coupe',
    drivetrain: 'RWD'
  },
  {
    id: 'car-6',
    make: 'Lexus',
    model: 'RX 350',
    year: 2023,
    price: 52000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1549399810-162c4763a7ea?w=800',
    dealershipId: 'dealership-1',
    features: ['Safety System 2.0', 'Mark Levinson Audio', 'Moonroof', 'Heated/Cooled Seats', 'Wireless Charging'],
    color: 'Atomic Silver',
    mileage: 15000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-7',
    make: 'Tesla',
    model: 'Model Y',
    year: 2024,
    price: 52990,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    dealershipId: 'dealership-1',
    features: ['Autopilot', 'Premium Connectivity', 'Glass Roof', 'Heated Seats', 'Over-the-Air Updates'],
    color: 'Midnight Silver',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-8',
    make: 'BMW',
    model: 'M3',
    year: 2023,
    price: 78500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    dealershipId: 'dealership-1',
    features: ['M Performance Package', 'Carbon Fiber Trim', 'Harman Kardon Audio', 'M Sport Seats', 'Launch Control'],
    color: 'Alpine White',
    mileage: 5000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },
  {
    id: 'car-9',
    make: 'Mercedes-Benz',
    model: 'GLE 350',
    year: 2024,
    price: 68500,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b6c92669?w=800',
    dealershipId: 'dealership-1',
    features: ['MBUX AR Navigation', 'Air Suspension', 'Premium Package', 'Burmester Audio', 'Panoramic Roof'],
    color: 'Iridium Silver',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-10',
    make: 'Audi',
    model: 'A4',
    year: 2023,
    price: 42000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    dealershipId: 'dealership-1',
    features: ['Virtual Cockpit Plus', 'Quattro AWD', 'Premium Plus Package', 'Bang & Olufsen Audio', 'Adaptive Cruise'],
    color: 'Brilliant Black',
    mileage: 18000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'AWD'
  },
  {
    id: 'car-11',
    make: 'Cadillac',
    model: 'Escalade',
    year: 2024,
    price: 89000,
    seats: 8,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800',
    dealershipId: 'dealership-1',
    features: ['Super Cruise', 'AKG Studio Audio', 'Magnetic Ride Control', 'Night Vision', 'Curved OLED Display'],
    color: 'Shadow Metallic',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-12',
    make: 'Jaguar',
    model: 'F-PACE',
    year: 2023,
    price: 55500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800',
    dealershipId: 'dealership-1',
    features: ['Pivi Pro Infotainment', 'All-Wheel Drive', 'Meridian Audio', 'Activity Key', 'Wade Sensing'],
    color: 'Loire Blue',
    mileage: 22000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-13',
    make: 'Genesis',
    model: 'G90',
    year: 2024,
    price: 75000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
    dealershipId: 'dealership-1',
    features: ['Lexicon Audio', 'Highway Driving Assist 2', 'Biometric Entry', 'Nappa Leather', 'Air Suspension'],
    color: 'Uyuni White',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'AWD'
  },
  {
    id: 'car-14',
    make: 'Range Rover',
    model: 'Evoque',
    year: 2023,
    price: 48000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1594736797933-d0301ba2fe65?w=800',
    dealershipId: 'dealership-1',
    features: ['ClearSight Rear Mirror', 'Terrain Response 2', 'Meridian Audio', 'Panoramic Roof', 'Wade Sensing'],
    color: 'Corris Grey',
    mileage: 14000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-15',
    make: 'Maserati',
    model: 'Ghibli',
    year: 2023,
    price: 82000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    dealershipId: 'dealership-1',
    features: ['Harman Kardon Audio', 'Skyhook Suspension', 'Leather Interior', 'Brembo Brakes', 'Sport Mode'],
    color: 'Nero Ribelle',
    mileage: 8000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },
  {
    id: 'car-16',
    make: 'Volvo',
    model: 'XC90',
    year: 2024,
    price: 58000,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    dealershipId: 'dealership-1',
    features: ['Pilot Assist', 'Bowers & Wilkins Audio', 'Air Suspension', 'Crystal Gearshift', 'Thor\'s Hammer Lights'],
    color: 'Crystal White',
    mileage: 0,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-17',
    make: 'Alfa Romeo',
    model: 'Giulia',
    year: 2023,
    price: 45000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    dealershipId: 'dealership-1',
    features: ['8.8" Touchscreen', 'DNA Pro Drive Mode', 'Premium Package', 'Performance Brakes', 'Sport Steering'],
    color: 'Rosso Competizione',
    mileage: 16000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },

  // Metro Motors (Austin) - 17 cars
  {
    id: 'car-18',
    make: 'Ford',
    model: 'F-150 Lightning',
    year: 2024,
    price: 58000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
    dealershipId: 'dealership-2',
    features: ['Pro Power Onboard', 'BlueCruise', 'Ford SYNC 4A', 'LED Work Lights', 'Intelligent Backup Power'],
    color: 'Antimatter Blue',
    mileage: 0,
    fuelType: 'Electric',
    transmission: 'Automatic',
    bodyType: 'Truck',
    drivetrain: 'AWD'
  },
  {
    id: 'car-19',
    make: 'Chevrolet',
    model: 'Silverado',
    year: 2023,
    price: 42000,
    seats: 6,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1549399810-162c4763a7ea?w=800',
    dealershipId: 'dealership-2',
    features: ['Chevy Safety Assist', 'Bose Audio', 'Wireless Charging', 'Bed Liner', 'Tow Package'],
    color: 'Summit White',
    mileage: 25000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Truck',
    drivetrain: '4WD'
  },
  {
    id: 'car-20',
    make: 'Toyota',
    model: 'Prius',
    year: 2024,
    price: 32000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    dealershipId: 'dealership-2',
    features: ['Toyota Safety Sense 2.0', 'JBL Audio', 'Wireless Charging', 'Smart Key', 'Eco Mode'],
    color: 'Supersonic Red',
    mileage: 0,
    fuelType: 'Hybrid',
    transmission: 'CVT',
    bodyType: 'Hatchback',
    drivetrain: 'FWD'
  },
  {
    id: 'car-21',
    make: 'Honda',
    model: 'Accord',
    year: 2023,
    price: 28500,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    dealershipId: 'dealership-2',
    features: ['Honda Sensing', 'Wireless Android Auto', 'Remote Start', 'LED Headlights', 'Dual-Zone Climate'],
    color: 'Platinum White Pearl',
    mileage: 18000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-22',
    make: 'Nissan',
    model: 'Altima',
    year: 2023,
    price: 26000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    dealershipId: 'dealership-2',
    features: ['ProPILOT Assist', 'Bose Audio', 'Intelligent Key', 'Remote Engine Start', 'Safety Shield 360'],
    color: 'Gun Metallic',
    mileage: 32000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-23',
    make: 'Mazda',
    model: 'CX-5',
    year: 2024,
    price: 34000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    dealershipId: 'dealership-2',
    features: ['i-ACTIVSENSE', 'Bose Audio', 'Apple CarPlay', 'Leather Seats', 'Power Liftgate'],
    color: 'Soul Red Crystal',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-24',
    make: 'Subaru',
    model: 'Outback',
    year: 2023,
    price: 31000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b6c92669?w=800',
    dealershipId: 'dealership-2',
    features: ['EyeSight Driver Assist', 'Harman Kardon Audio', 'X-Mode', 'Roof Rails', 'All-Weather Package'],
    color: 'Autumn Green Metallic',
    mileage: 22000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Wagon',
    drivetrain: 'AWD'
  },
  {
    id: 'car-25',
    make: 'Hyundai',
    model: 'Tucson',
    year: 2024,
    price: 29500,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    dealershipId: 'dealership-2',
    features: ['SmartSense Safety Suite', 'Bose Audio', 'Wireless Charging', 'Digital Key', 'Panoramic Sunroof'],
    color: 'Amazon Gray',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-26',
    make: 'Kia',
    model: 'Sportage',
    year: 2023,
    price: 27500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    dealershipId: 'dealership-2',
    features: ['Drive Wise Safety Tech', 'Harman Kardon Audio', 'Smart Key', 'Roof Rails', 'Terrain Modes'],
    color: 'Jungle Green',
    mileage: 15000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-27',
    make: 'Jeep',
    model: 'Wrangler',
    year: 2024,
    price: 38000,
    seats: 4,
    safetyRating: 3,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    dealershipId: 'dealership-2',
    features: ['Removable Doors/Roof', 'Rock-Trac 4WD', 'Alpine Audio', 'LED Lighting', 'All-Terrain Tires'],
    color: 'Firecracker Red',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Manual',
    bodyType: 'SUV',
    drivetrain: '4WD'
  },
  {
    id: 'car-28',
    make: 'RAM',
    model: '1500',
    year: 2023,
    price: 45000,
    seats: 6,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1558618047-3c8c76ca7d13?w=800',
    dealershipId: 'dealership-2',
    features: ['Uconnect 5', 'Harman Kardon Audio', 'Air Suspension', 'Multifunction Tailgate', 'RamBox Storage'],
    color: 'Granite Crystal',
    mileage: 28000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Truck',
    drivetrain: '4WD'
  },
  {
    id: 'car-29',
    make: 'GMC',
    model: 'Sierra',
    year: 2024,
    price: 48000,
    seats: 6,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1549399810-162c4763a7ea?w=800',
    dealershipId: 'dealership-2',
    features: ['GMC Pro Safety Plus', 'Bose Audio', 'MultiPro Tailgate', 'CarbonPro Bed', 'Traction Select'],
    color: 'Onyx Black',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Truck',
    drivetrain: '4WD'
  },
  {
    id: 'car-30',
    make: 'Acura',
    model: 'MDX',
    year: 2023,
    price: 52000,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    dealershipId: 'dealership-2',
    features: ['AcuraWatch', 'ELS Studio 3D Audio', 'Super Handling SH-AWD', 'Panoramic Moonroof', 'Wireless Charging'],
    color: 'Majestic Black Pearl',
    mileage: 19000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-31',
    make: 'Infiniti',
    model: 'QX60',
    year: 2024,
    price: 49000,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606664515524-ed2f786a0bd6?w=800',
    dealershipId: 'dealership-2',
    features: ['ProPILOT Assist', 'Bose Audio', 'Tri-Zone Climate', 'Motion Activated Liftgate', 'Around View Monitor'],
    color: 'Liquid Platinum',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-32',
    make: 'Buick',
    model: 'Enclave',
    year: 2023,
    price: 44000,
    seats: 8,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800',
    dealershipId: 'dealership-2',
    features: ['Buick Driver Confidence', 'Bose Audio', 'Hands-Free Power Liftgate', 'Heated/Cooled Seats', 'Tri-Zone Climate'],
    color: 'Ebony Twilight',
    mileage: 35000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-33',
    make: 'Lincoln',
    model: 'Aviator',
    year: 2024,
    price: 58000,
    seats: 7,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=800',
    dealershipId: 'dealership-2',
    features: ['Lincoln Co-Pilot360', 'Revel Audio', 'Air Suspension', 'Phone As A Key', 'Panoramic Vista Roof'],
    color: 'Crystal Red',
    mileage: 0,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-34',
    make: 'Volkswagen',
    model: 'Atlas',
    year: 2023,
    price: 36000,
    seats: 8,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1617531653332-bd46c24f2068?w=800',
    dealershipId: 'dealership-2',
    features: ['IQ.Drive', 'Fender Audio', 'Digital Cockpit', 'App-Connect', 'Panoramic Sunroof'],
    color: 'Pure White',
    mileage: 21000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },

  // Northeast Car Connection (Boston) - 16 cars
  {
    id: 'car-35',
    make: 'Toyota',
    model: 'Camry',
    year: 2024,
    price: 28000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    dealershipId: 'dealership-3',
    features: ['Toyota Safety Sense 2.0', 'JBL Audio', 'Wireless Charging', 'Smart Key', 'Adaptive Cruise Control'],
    color: 'Wind Chill Pearl',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-36',
    make: 'Honda',
    model: 'CR-V',
    year: 2023,
    price: 32000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    dealershipId: 'dealership-3',
    features: ['Honda Sensing', 'Bose Audio', 'Hands-Free Power Tailgate', 'Remote Start', 'All-Wheel Drive'],
    color: 'Modern Steel Metallic',
    mileage: 24000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-37',
    make: 'Mazda',
    model: 'Mazda3',
    year: 2024,
    price: 24500,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    dealershipId: 'dealership-3',
    features: ['i-ACTIVSENSE', 'Bose Audio', 'Apple CarPlay', 'Premium Package', 'Sunroof'],
    color: 'Polymetal Gray',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Hatchback',
    drivetrain: 'FWD'
  },
  {
    id: 'car-38',
    make: 'Subaru',
    model: 'Forester',
    year: 2023,
    price: 29000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1606152421802-db97b6c92669?w=800',
    dealershipId: 'dealership-3',
    features: ['EyeSight Driver Assist', 'Harman Kardon Audio', 'X-Mode', 'Power Rear Gate', 'Roof Rails'],
    color: 'Horizon Blue Pearl',
    mileage: 18000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-39',
    make: 'Volkswagen',
    model: 'Jetta',
    year: 2024,
    price: 22500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    dealershipId: 'dealership-3',
    features: ['IQ.Drive', 'BeatsAudio', 'App-Connect', 'Digital Cockpit', 'Sunroof'],
    color: 'Tornado Red',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-40',
    make: 'Hyundai',
    model: 'Elantra',
    year: 2023,
    price: 23000,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    dealershipId: 'dealership-3',
    features: ['SmartSense Safety Suite', 'Bose Audio', 'Wireless Charging', 'Digital Key', 'Sunroof'],
    color: 'Intense Blue',
    mileage: 26000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-41',
    make: 'Kia',
    model: 'Forte',
    year: 2024,
    price: 21000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1618843479313-40f8afb4b4d8?w=800',
    dealershipId: 'dealership-3',
    features: ['Drive Wise Safety Tech', 'Premium Audio', 'UVO eServices', 'Wireless Charging', 'Sunroof'],
    color: 'Aurora Black',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-42',
    make: 'Nissan',
    model: 'Sentra',
    year: 2023,
    price: 20500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1621007947382-bb3c3994e3fb?w=800',
    dealershipId: 'dealership-3',
    features: ['Safety Shield 360', 'Bose Audio', 'Intelligent Key', 'Remote Engine Start', 'Sunroof'],
    color: 'Super Black',
    mileage: 30000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-43',
    make: 'Chevrolet',
    model: 'Malibu',
    year: 2024,
    price: 25500,
    seats: 5,
    safetyRating: 5,
    imageUrl: 'https://images.unsplash.com/photo-1560958089-b8a1929cea89?w=800',
    dealershipId: 'dealership-3',
    features: ['Chevy Safety Assist', 'Bose Audio', 'Wireless Charging', 'Remote Start', 'Teen Driver'],
    color: 'Summit White',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'Sedan',
    drivetrain: 'FWD'
  },
  {
    id: 'car-44',
    make: 'Ford',
    model: 'Escape',
    year: 2023,
    price: 28500,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1544636331-e26879cd4d9b?w=800',
    dealershipId: 'dealership-3',
    features: ['Ford Co-Pilot360', 'B&O Audio', 'Intelligent AWD', 'Hands-Free Liftgate', 'Wireless Charging'],
    color: 'Rapid Red',
    mileage: 16000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-45',
    make: 'Jeep',
    model: 'Compass',
    year: 2024,
    price: 26000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    dealershipId: 'dealership-3',
    features: ['Advanced Safety Features', 'Alpine Audio', 'Uconnect 4C', 'All-Weather Capable', 'Roof Rails'],
    color: 'Granite Crystal',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: '4WD'
  },
  {
    id: 'car-46',
    make: 'Mitsubishi',
    model: 'Outlander',
    year: 2023,
    price: 27000,
    seats: 7,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800',
    dealershipId: 'dealership-3',
    features: ['MI-PILOT Assist', 'Rockford Fosgate Audio', 'Super All-Wheel Control', 'Hands-Free Power Liftgate', 'Panoramic Sunroof'],
    color: 'Diamond White Pearl',
    mileage: 22000,
    fuelType: 'Gas',
    transmission: 'CVT',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  },
  {
    id: 'car-47',
    make: 'Dodge',
    model: 'Charger',
    year: 2024,
    price: 35000,
    seats: 5,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?w=800',
    dealershipId: 'dealership-3',
    features: ['Advanced Safety Group', 'Alpine Audio', 'Uconnect 4C', 'Performance Pages', 'Sport Mode'],
    color: 'F8 Green',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Sedan',
    drivetrain: 'RWD'
  },
  {
    id: 'car-48',
    make: 'Chrysler',
    model: 'Pacifica',
    year: 2023,
    price: 38000,
    seats: 8,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1631295868223-63265b40d9e4?w=800',
    dealershipId: 'dealership-3',
    features: ['Advanced SafetyTec Group', 'Harman Kardon Audio', 'Stow \'n Go Seating', 'Uconnect Theater', 'Hands-Free Doors'],
    color: 'Ceramic Grey',
    mileage: 28000,
    fuelType: 'Hybrid',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'FWD'
  },
  {
    id: 'car-49',
    make: 'MINI',
    model: 'Cooper',
    year: 2024,
    price: 32000,
    seats: 4,
    safetyRating: 4,
    imageUrl: 'https://images.unsplash.com/photo-1544829099-b9a0c5303bea?w=800',
    dealershipId: 'dealership-3',
    features: ['MINI Connected Services', 'Harman Kardon Audio', 'Panoramic Sunroof', 'Driving Modes', 'LED Lights'],
    color: 'British Racing Green',
    mileage: 0,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'Hatchback',
    drivetrain: 'FWD'
  },
  {
    id: 'car-50',
    make: 'Fiat',
    model: '500X',
    year: 2023,
    price: 24000,
    seats: 5,
    safetyRating: 3,
    imageUrl: 'https://images.unsplash.com/photo-1617788138017-80ad40651399?w=800',
    dealershipId: 'dealership-3',
    features: ['Advanced Safety Features', 'BeatsAudio', 'Uconnect 4', 'All-Weather Capable', 'Sport Mode'],
    color: 'Glacier Blue',
    mileage: 31000,
    fuelType: 'Gas',
    transmission: 'Automatic',
    bodyType: 'SUV',
    drivetrain: 'AWD'
  }
];
